# Generated by Django 5.1.3 on 2024-12-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='profile',
        ),
    ]
