# Generated by Django 5.1.3 on 2024-12-08 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_log_profile'),
        ('profiles', '0003_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
